### ISSUE TITLE
Running Into Issue Creating Server. Am I Missing Something?

### ISSUE THREAD

**Issue by flancast90** [appy-one/acebase-server#27] opened 2022-07-21 01:33 UTC
Hi, 
I've begun migrating my project to AceBase, and while the regular AceBase library works fine, as soon as I attempt to integrate with AceBase-Server, I get an error (see bottom of issue). Mainly, I'm confused as to how the code should look (e.g. do I need both an AceBase and AceBase-server instance)? 

The issue is probably just an issue with how I've imported everything, so I'd appreciate some guidance on how to fix :)

My Code:
```js
import { AceBase } from 'acebase'
const db = new AceBase('db');

import { AceBaseServer } from 'acebase-server';
const server = new AceBaseServer('db', { host: 'localhost', port: 5757 });
```

Error Message:
```
[db] DEBUG THIS: getNodeInfo error Error: Not enough bytes read from file at index 131072, expected 128 but got 0
    at NodeReader.readHeader (C:\Users\Finn Lancaster\Desktop\Finned-Backend\node_modules\acebase\src\storage-acebase.js:3051:49)
    at async start (C:\Users\Finn Lancaster\Desktop\Finned-Backend\node_modules\acebase\src\storage-acebase.js:2649:17)
    at async NodeReader.getChildInfo (C:\Users\Finn Lancaster\Desktop\Finned-Backend\node_modules\acebase\src\storage-acebase.js:2956:9)
    at async AceBaseStorage.getNodeInfo (C:\Users\Finn Lancaster\Desktop\Finned-Backend\node_modules\acebase\src\storage-acebase.js:1725:33)
    at async AceBaseStorage.getNodeInfo (C:\Users\Finn Lancaster\Desktop\Finned-Backend\node_modules\acebase\src\storage-acebase.js:1701:34)
    at async AceBaseStorage.getNodeInfo (C:\Users\Finn Lancaster\Desktop\Finned-Backend\node_modules\acebase\src\storage-acebase.js:1701:34)
    at async AceBaseStorage.getNode (C:\Users\Finn Lancaster\Desktop\Finned-Backend\node_modules\acebase\src\storage-acebase.js:1587:30)
    at async AceBaseStorage.transactNode (C:\Users\Finn Lancaster\Desktop\Finned-Backend\node_modules\acebase\src\storage.js:1274:26)
    at async LocalApi.transaction (C:\Users\Finn Lancaster\Desktop\Finned-Backend\node_modules\acebase\src\api-local.js:133:24)
    at async DataReference.transaction (C:\Users\Finn Lancaster\Desktop\Finned-Backend\node_modules\acebase-core\dist\cjs\data-reference.js:293:28)
[db] DEBUG THIS: getNodeInfo error Error: Not enough bytes read from file at index 131072, expected 128 but got 0
    at NodeReader.readHeader (C:\Users\Finn Lancaster\Desktop\Finned-Backend\node_modules\acebase\src\storage-acebase.js:3051:49)
    at async start (C:\Users\Finn Lancaster\Desktop\Finned-Backend\node_modules\acebase\src\storage-acebase.js:2649:17)
    at async NodeReader.getChildInfo (C:\Users\Finn Lancaster\Desktop\Finned-Backend\node_modules\acebase\src\storage-acebase.js:2956:9)
    at async AceBaseStorage.getNodeInfo (C:\Users\Finn Lancaster\Desktop\Finned-Backend\node_modules\acebase\src\storage-acebase.js:1725:33)
    at async AceBaseStorage.getNodeInfo (C:\Users\Finn Lancaster\Desktop\Finned-Backend\node_modules\acebase\src\storage-acebase.js:1701:34)
    at async AceBaseStorage.getNodeInfo (C:\Users\Finn Lancaster\Desktop\Finned-Backend\node_modules\acebase\src\storage-acebase.js:1701:34)
    at async AceBaseStorage.getNode (C:\Users\Finn Lancaster\Desktop\Finned-Backend\node_modules\acebase\src\storage-acebase.js:1587:30)
    at async AceBaseStorage.transactNode (C:\Users\Finn Lancaster\Desktop\Finned-Backend\node_modules\acebase\src\storage.js:1274:26)
    at async LocalApi.transaction (C:\Users\Finn Lancaster\Desktop\Finned-Backend\node_modules\acebase\src\api-local.js:133:24)
    at async DataReference.transaction (C:\Users\Finn Lancaster\Desktop\Finned-Backend\node_modules\acebase-core\dist\cjs\data-reference.js:293:28)
[db] DEBUG THIS: getNodeInfo error Error: Not enough bytes read from file at index 131072, expected 128 but got 0      
    at NodeReader.readHeader (C:\Users\Finn Lancaster\Desktop\Finned-Backend\node_modules\acebase\src\storage-acebase.js:3051:49)
    at async start (C:\Users\Finn Lancaster\Desktop\Finned-Backend\node_modules\acebase\src\storage-acebase.js:2649:17)
    at async NodeReader.getChildInfo (C:\Users\Finn Lancaster\Desktop\Finned-Backend\node_modules\acebase\src\storage-acebase.js:2956:9)
    at async AceBaseStorage.getNodeInfo (C:\Users\Finn Lancaster\Desktop\Finned-Backend\node_modules\acebase\src\storage-acebase.js:1725:33)
    at async AceBaseStorage.getNodeInfo (C:\Users\Finn Lancaster\Desktop\Finned-Backend\node_modules\acebase\src\storage-acebase.js:1701:34)
    at async AceBaseStorage.getNodeInfo (C:\Users\Finn Lancaster\Desktop\Finned-Backend\node_modules\acebase\src\storage-acebase.js:1701:34)
    at async AceBaseStorage.getNode (C:\Users\Finn Lancaster\Desktop\Finned-Backend\node_modules\acebase\src\storage-acebase.js:1587:30)
    at async AceBaseStorage.transactNode (C:\Users\Finn Lancaster\Desktop\Finned-Backend\node_modules\acebase\src\storage.js:1274:26)
    at async LocalApi.transaction (C:\Users\Finn Lancaster\Desktop\Finned-Backend\node_modules\acebase\src\api-local.js:133:24)
    at async DataReference.transaction (C:\Users\Finn Lancaster\Desktop\Finned-Backend\node_modules\acebase-core\dist\cjs\data-reference.js:293:28)
[db] DEBUG THIS: getNode error: Error: Not enough bytes read from file at index 131072, expected 128 but got 0
    at NodeReader.readHeader (C:\Users\Finn Lancaster\Desktop\Finned-Backend\node_modules\acebase\src\storage-acebase.js:3051:49)
    at async start (C:\Users\Finn Lancaster\Desktop\Finned-Backend\node_modules\acebase\src\storage-acebase.js:2649:17)
    at async NodeReader.getChildInfo (C:\Users\Finn Lancaster\Desktop\Finned-Backend\node_modules\acebase\src\storage-acebase.js:2956:9)
    at async AceBaseStorage.getNodeInfo (C:\Users\Finn Lancaster\Desktop\Finned-Backend\node_modules\acebase\src\storage-acebase.js:1725:33)
    at async AceBaseStorage.getNodeInfo (C:\Users\Finn Lancaster\Desktop\Finned-Backend\node_modules\acebase\src\storage-acebase.js:1701:34)
    at async AceBaseStorage.getNodeInfo (C:\Users\Finn Lancaster\Desktop\Finned-Backend\node_modules\acebase\src\storage-acebase.js:1701:34)
    at async AceBaseStorage.getNode (C:\Users\Finn Lancaster\Desktop\Finned-Backend\node_modules\acebase\src\storage-acebase.js:1587:30)
    at async AceBaseStorage.transactNode (C:\Users\Finn Lancaster\Desktop\Finned-Backend\node_modules\acebase\src\storage.js:1274:26)
    at async LocalApi.transaction (C:\Users\Finn Lancaster\Desktop\Finned-Backend\node_modules\acebase\src\api-local.js:133:24)
    at async DataReference.transaction (C:\Users\Finn Lancaster\Desktop\Finned-Backend\node_modules\acebase-core\dist\cjs\data-reference.js:293:28)
node:internal/process/promises:279
            triggerUncaughtException(err, true /* fromPromise */);
            ^

Error: Not enough bytes read from file at index 131072, expected 128 but got 0
    at NodeReader.readHeader (C:\Users\Finn Lancaster\Desktop\Finned-Backend\node_modules\acebase\src\storage-acebase.js:3051:49)
    at async start (C:\Users\Finn Lancaster\Desktop\Finned-Backend\node_modules\acebase\src\storage-acebase.js:2649:17)
    at async NodeReader.getChildInfo (C:\Users\Finn Lancaster\Desktop\Finned-Backend\node_modules\acebase\src\storage-acebase.js:2956:9)
    at async AceBaseStorage.getNodeInfo (C:\Users\Finn Lancaster\Desktop\Finned-Backend\node_modules\acebase\src\storage-acebase.js:1725:33)
    at async AceBaseStorage.getNodeInfo (C:\Users\Finn Lancaster\Desktop\Finned-Backend\node_modules\acebase\src\storage-acebase.js:1701:34)
    at async AceBaseStorage.getNodeInfo (C:\Users\Finn Lancaster\Desktop\Finned-Backend\node_modules\acebase\src\storage-acebase.js:1701:34)
    at async AceBaseStorage.getNode (C:\Users\Finn Lancaster\Desktop\Finned-Backend\node_modules\acebase\src\storage-acebase.js:1587:30)
    at async AceBaseStorage.transactNode (C:\Users\Finn Lancaster\Desktop\Finned-Backend\node_modules\acebase\src\storage.js:1274:26)
    at async LocalApi.transaction (C:\Users\Finn Lancaster\Desktop\Finned-Backend\node_modules\acebase\src\api-local.js:133:24)
    at async DataReference.transaction (C:\Users\Finn Lancaster\Desktop\Finned-Backend\node_modules\acebase-core\dist\cjs\data-reference.js:293:28)
```

**Comment by donl** [comment] 2022-07-26 02:02
Try removing
``` js
const db = new AceBase('db');
```

Otherwise you are creating/accessing the same database named 'db' on disk multiple times simultaneously, which requires special coordination.

**Comment by flancast90** [comment] 2022-07-26 02:22
I tried both with and without that line, and got the same issue either way.
Any other ideas?

**Comment by appy-one** [comment] 2022-07-26 19:14
It looks like you may have corrupted the database file by accessing (writing to) it from both an `AceBaseServer` and local `AceBase` db instance, I posted about this a while ago in the discussion ["How to protect your database from corruption"](https://github.com/appy-one/acebase/discussions/48).

If the data you stored in the db is important, I might be able to help you recover the data. If it only has dev/test data, I recommend removing it and starting over with a fresh db. Make sure you only let a single `AceBaseServer` instance access the database files, or configure an [acebase-ipc-server](https://github.com/appy-one/acebase-ipc-server) to setup a cluster.

**Comment by flancast90** [comment] 2022-07-29 19:52
I tried using only one of the instances and deleting the existing db to
allow it to create a fresh one, with the same issue. In terms of recovery,
I never actually got it to work, so there was no data in it.

**Comment by appy-one** [comment] 2022-07-30 19:22
Alright, you'll have to provide more code to reproduce this then. Only importing `AceBaseServer` and instantiating it with a new db does not cause any issues in my tests?

**Comment by appy-one** [comment] 2022-08-19 20:00
I'm closing this issue for now. If you have more info about how to reproduce this, feel free to reopen!

**Closed by appy-one** 2022-08-19 20:00 UTC
